[skip azp][Circleci] Added deploy job to cluster and ingress

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,8 +7,11 @@ parameters:
     default: true
   run_deploy_infrastructure:
     type: boolean
-    default: true  
+    default: false  
   run_configure_infrastructure:
+    type: boolean
+    default: false  
+  run_deploy_app:
     type: boolean
     default: true  
 commands:
@@ -231,9 +234,10 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
+            # curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+            # curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
             # echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check >/dev/null 2>&1 || \
+            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
             sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
             sudo apt update
             sudo apt install -y python3-pip
@@ -298,9 +302,10 @@ jobs:
       - run:
           name: Install dependencies
           command: |
-            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-            curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
+            # curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+            # curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
             # echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check >/dev/null 2>&1 || \
+            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
             sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
             #kubectl version --short
             curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
@@ -317,6 +322,9 @@ jobs:
             sudo apt-get update
             sudo apt-get install helm
             helm version
+            sudo apt update
+            sudo apt install -y python3-pip
+            pip3 install envsubst            
       - run:
           name: Configure kubectl
           command: |
@@ -361,6 +369,85 @@ jobs:
           when: on_fail
           command: |
             kubectl delete deployment -n kube-system aws-load-balancer-controller || true
+#  
+  deploy-app:
+    docker:
+      - image: cimg/base:2020.05
+    steps:
+      - check_job:
+          start_job: <<pipeline.parameters.run_deploy_app>>
+      - checkout
+      - install_aws      
+      - configure_aws:
+          access_key_id: $AWS_ADMIN_ACCESS_KEY_ID
+          secret_access_key: $AWS_ADMIN_SECRET_ACCESS_KEY
+      - run:
+          name: Install dependencies
+          command: |
+            # curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+            # curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
+            # echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check >/dev/null 2>&1 || \
+            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.23.7/2022-06-29/bin/linux/amd64/kubectl
+            sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
+            kubectl version --short
+            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
+             | tar xz -C /tmp
+            sudo mv /tmp/eksctl /usr/local/bin
+            eksctl version
+            curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
+            sudo apt-get install apt-transport-https --yes
+            echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
+            sudo apt-get update
+            sudo apt-get install helm
+            helm version
+            sudo apt install -y python3-pip
+            pip3 install envsubst            
+      - run:
+          name: Configure kubectl
+          command: |
+            aws eks update-kubeconfig --name ${CLUSTERNAME}
+            # aws eks describe-cluster --name ${CLUSTERNAME} 	
+     	- run: 
+     			name: Configure dockerhub secrets
+     			command: |
+            DOCKERHUB_USERNAME=$(aws ssm get-parameter \
+            --name /aws/reference/secretsmanager/dockerhub \
+            --with-decryption --output text --query "Parameter.Value" | jq -r ."username")
+            DOCKERHUB_PASSWORD=$(aws ssm get-parameter \
+            --name /aws/reference/secretsmanager/dockerhub \
+            --with-decryption --output text --query "Parameter.Value" | jq -r ."password") 
+            kubectl create secret docker-registry dockerhub \
+            --docker-server=docker.io \
+            --docker-username=$DOCKERHUB_USERNAME \
+            --docker-password=$DOCKERHUB_PASSWORD								
+      - run:
+      		name: Deploy App environment to cluster
+      		command: |
+            # Set environment variables
+            export DOCKERHUB_USERNAME=$(aws ssm get-parameter \
+            --name /aws/reference/secretsmanager/dockerhub \
+            --with-decryption --output text --query "Parameter.Value" | jq -r ."username")      		
+            export WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:7} 
+            # Deploy latest version of App
+            envsubst < manifests/deployment.yml | tee deployment.yml > /dev/null
+            kubectl apply -f ./deployment.yml
+            kubectl rollout status -f deployment.yml --timeout=10s | grep -oh 'deployment "notebook-£{WORKFLOW_ID}" successfully rolled out' || echo exit 1 
+            kubectl get pods -l app=notebook-${WORKFLOW_ID} 
+            envsubst < manifests/service.yml | tee service.yml > /dev/null
+            kubectl apply -f ./service.yml 
+            kubectl describe service notebook-${WORKFLOW_ID}
+      - run:
+          name: Ensure prod environment exist
+          command: |
+            kubectl exec -it -c notebook $(kubectl get pod -l app=notebook-${WORKFLOW_ID} -o name | head -n 1) -- npm run ping								
+      - run:
+          name: Rollback deployment 
+          command: |
+            export WORKFLOW_ID=${CIRCLE_WORKFLOW_ID:0:7} 
+            echo "Notebook environment deployment failed"
+            kubectl delete deployment/notebook-${WORKFLOW_ID} || true
+            kubectl delete svc notebook-${WORKFLOW_ID} || true
+        condition: on_fail            
 # build-app job is run on tags since the docker image pulled in production is tagged with same Workflow ID             
 workflows:
   default:
@@ -395,3 +482,11 @@ workflows:
             - aws-context
           filters:
             <<: *filters-production
+      - deploy-app:
+          requires: 
+            - configure-infrastructure              
+          context:
+            - org-global
+            - aws-context
+          filters:
+            <<: *filters-production            
